### ISSUE TITLE
Investigate Lantern incompatibility with Xunlei

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern#3679]

**Comment by fffw** [comment]
This issue seems to have being fixed in the latest version of Xunlei (7.9.43.5054) and Xunlei express (1.0.33.358). Leave it open for a while to make sure.

**Comment by fffw** [comment]
I set Lantern to proxy all traffic, and confirmed from logs that all requests are proxied. Findings so far:

1. Able to visit blocked plain HTTP sites from browser.

2. Visit blocked HTTPS sites from browser, always EOF.

Below are relevant log entries. I changed `handler.go` a bit to show which operation actually causes problem.
```
Mar 31 13:07:28.822 - 0m9s DEBUG balancer: balancer.go:95 Successfully dialed via (trusted) chained proxy at <masked> to connect://en.wikipedia.org:443 on pass 0
Mar 31 13:07:28.822 - 0m9s DEBUG flashlight.client: handler.go:175 Responding OK to //en.wikipedia.org:443
Mar 31 13:07:28.822 - 0m9s DEBUG flashlight.client: handler.go:188 Responding 200 to //en.wikipedia.org:443
Mar 31 13:07:36.166 - 0m16s TRACE flashlight.client: handler.go:157 Error read from connOut: EOF
Mar 31 13:07:36.166 - 0m16s TRACE flashlight.client: handler.go:149 Error piping data from client to proxy: read tcp 127.0.0.1:8787->127.0.0.1:52062: use of closed network connection
Mar 31 13:07:36.487 - 0m17s TRACE flashlight.client: handler.go:157 Error read from connOut: EOF
Mar 31 13:07:36.487 - 0m17s TRACE flashlight.client: handler.go:149 Error piping data from client to proxy: read tcp 127.0.0.1:8787->127.0.0.1:52067: use of closed network connection
```

3. Able to visit mimicking page of proxy from browser.

4. Able to visit domestic HTTPS sites from browser.

5. Able to visit any blocked sites via `curl`, e.g., `curl -vLx localhost:8787 https://en.wikipedia.org`.

The result is weird to me as 2 and 5 should be indistinguishable from outbound connection. As WireShark can't see any interfaces (even run as administrator) on Win 10 VM, I can't capture packets to see what actually happens. Maybe try again on Win 7.

**Comment by fffw** [comment]
So Xunlei installs a [WFP](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366510(v=vs.85).aspx) driver named `XLWFP` during installation, which causes all the trouble. It's located at `C:\Windows\system32\drivers\xlwfp.sys`. By `querydrivers /v` we can see its existence. 

Instead of detecting that specific software, we can run diagnostics in [self help page](https://github.com/getlantern/lantern/issues/3288).

**Comment by percyalpha** [comment]
Users continue to report such incompatibility. This is a high priority because most users in China have Xunlei installed.

**Comment by xiam** [comment]
I'll investigate this too.

**Comment by xiam** [comment]
@percyalpha Can you confirm this is still happening with Xunlei 7.9? 

@fffw I could not reproduce the HTTPs problem and I confirmed the `XLWFP.SYS` file was in place, to me latest QA versions works fine with Xunlei 7.9. After all my testing I only had problems with Xunlei 5 on Windows 7.

**Comment by xiam** [comment]
Hey @Rice321, could you help me testing latest QA + Xunlei too?

**Comment by Rice321** [comment]
@xiam Hi JC, I just downloaded Xunlei 2.6.9 (1826) on my mac, and tried the latest QA, Lantern works fine for me, whatismyipaddress.com tells me my IP is 2604:a880:800:10::8d8:6001; and when I try without running Xunlei, the IP address is the same.

**Comment by percyalpha** [comment]
People are probably talking about issues on windows? I'll give test a bit
and give feedback soon.

**Comment by sunshine19090** [comment]
@percyalpha Is this working for you now?

**Comment by percyalpha** [comment]
Yes

On Wednesday, May 11, 2016, sunshine19090 <notifications@github.com> wrote:

> @percyalpha <https://github.com/percyalpha> Is this working for you now?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getlantern/lantern/issues/3679#issuecomment-218569925>
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)
(202) 780-5619
www.percya.com   @p3rcya <https://twitter.com/p3rcya>
Independent Internet freedom researcher
Former co-founder of GreatFire

**Comment by sunshine19090** [comment]
Thanks @percyalpha.
