### ISSUE TITLE
Win 10 Lantern无法使用，Android版本也翻不出去了，最快的服务器位置显示为“N/A”

### ISSUE THREAD

**Issue by iteratorlee** [getlantern/lantern#5956]
如题，不知大家都没有这种情况，连github都是关了lantern才上去的。望尽快修复

**Comment by Yoyun** [comment]
我的也是，win10，lantern4.1.1 一直处于连接中... 无法翻墙。望尽快修复

**Comment by Cppowboy** [comment]
之前用得好好的，突然就不能用了，看来不是个例啊。

**Comment by SJTUboy** [comment]
我这里也是

**Comment by SJTUboy** [comment]
之前是 HK 服务器的IP地址，我怀疑是被屏蔽了

**Comment by A0FWE3** [comment]
PC win8.1也是一直处于连接中

**Comment by gmvp3** [comment]
我也是，突然就不能用了

**Comment by RichardKuroshio** [comment]
几分钟前突然就挂了

**Comment by zodiac911** [comment]
GGWP

**Comment by bufhdy** [comment]
+1

**Comment by yz02010** [comment]
N/A，怎么回事儿？？？？？？

**Comment by zhongjimax** [comment]
我的也是

**Comment by baiking** [comment]
被墙的感觉啊

**Comment by dainslef** [comment]
同不能用了。

**Comment by merlin1985** [comment]
我win7也是，lantern4.1.1刚才还能登陆呢，今天才续费两年啊，不会悲剧吧！！

**Comment by zetaosun** [comment]
突然之間不能用，10多分鐘之前，pro版本的

**Comment by zaleGZL** [comment]
我只想知道刚刚发生了什么？怎么就突然不能用了。。。

**Comment by unixzii** [comment]
+1

**Comment by SJTUboy** [comment]
@oxtoacart

**Comment by dainslef** [comment]
刚刚试了下macOS，也不能用了，macOS版本10.13。

**Comment by MatthewAndersonCN** [comment]
我的也不能用了，Win10系统，服务器一直是N/A，一直在连接中。

**Comment by huaidanlk** [comment]
+1

**Comment by SJTUboy** [comment]
macOS 10.13 和 macOS 10.11.6 同不能用

**Comment by MatthewAndersonCN** [comment]
不仅是PC端，安卓7.0 PRO版也无法使用。

**Comment by cyumeng** [comment]
应该和操作系统无关，我试了几个平台都down了。

**Comment by gmvp3** [comment]
墙是无法翻越的

**Comment by watchzerg** [comment]
macOS 10.13，2017.10.5 21:45，连不上了

**Comment by zchazc** [comment]
WIN10 4.0.1也是之前为HK服务器，现在为N/A且不可用。

**Comment by bbbbblllll** [comment]
突然就挂掉了

**Comment by aumujun** [comment]
无法使用，安卓版无响应！

**Comment by 80068** [comment]
目前无法使用，处于无法连接状态

**Comment by unixzii** [comment]
The latest version of Lantern Pro doesn't work on my Windows 10, Android 7.0 and macOS High Sierra devices. I think there might be something wrong with the Lantern server, just hoping it can be recovered soon.

There is a piece of logcat:
```
Oct 05 13:51:41.388 - 0m10s Oct 05 13:51:41.388 - 0m10s Oct 05 13:51:41.388 - 0m10s ERROR balancer: balancer.go:182 Unable to dial via fp-sbtk1a-20170919-017 (47.74.32.227:443) to connect://globalconfig.flashlightproxy.com:443: Unable to dial server fp-sbtk1a-20170919-017 (47.74.32.227:443): tlsdialer: DialWithDialer timed out on pass 0...continuing [error=Unable to dial via %v to %s://%s: %v on pass %v...continuing error_location=github.com/getlantern/flashlight/balancer.(*Balancer).Dial (balancer.go:182) error_op= error_text=Unable to dial via fp-sbtk1a-20170919-017 (47.74.32.227:443) to connect://globalconfig.flashlightproxy.com:443: Unable to dial server fp-sbtk1a-20170919-017 (47.74.32.227:443): tlsdialer: DialWithDialer timed out on pass 0...continuing error_type=errors.Error op=dial_for_balancer proxy_host=47.74.32.227 proxy_port=443 proxy_type=chained root_op=dial_for_balancer]
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/balancer.(*Balancer).Dial (balancer.go:182)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/client.(*Client).getDialer.func2.1 (client.go:388)
ERROR balancer: balancer.go:182   at runtime.goexit (asm_amd64.s:2086)
ERROR balancer: balancer.go:182 Caused by: Unable to dial server fp-sbtk1a-20170919-017 (47.74.32.227:443): tlsdialer: DialWithDialer timed out
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/chained.(*proxy).dialInternal (dialer.go:190)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/chained.(*proxy).doDial (dialer.go:176)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/chained.(*proxy).Dial (dialer.go:131)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/balancer.(*Balancer).dialWithTimeout.func1 (balancer.go:212)
ERROR balancer: balancer.go:182   at runtime.goexit (asm_amd64.s:2086)
ERROR balancer: balancer.go:182 Caused by: tlsdialer: DialWithDialer timed out
ERROR balancer: balancer.go:182 Unable to dial via fp-sbtk1a-20170919-017 (47.74.32.227:443) to persistent://config.getiantem.org:80: Unable to dial server fp-sbtk1a-20170919-017 (47.74.32.227:443): tlsdialer: DialWithDialer timed out on pass 0...continuing [error=Unable to dial via %v to %s://%s: %v on pass %v...continuing error_location=github.com/getlantern/flashlight/balancer.(*Balancer).Dial (balancer.go:182) error_op= error_text=Unable to dial via fp-sbtk1a-20170919-017 (47.74.32.227:443) to persistent://config.getiantem.org:80: Unable to dial server fp-sbtk1a-20170919-017 (47.74.32.227:443): tlsdialer: DialWithDialer timed out on pass 0...continuing error_type=errors.Error op=dial_for_balancer proxy_host=47.74.32.227 proxy_port=443 proxy_type=chained root_op=dial_for_balancer]
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/balancer.(*Balancer).Dial (balancer.go:182)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/client.(*Client).getDialer.func2.1 (client.go:388)
ERROR balancer: balancer.go:182   at runtime.goexit (asm_amd64.s:2086)
ERROR balancer: balancer.go:182 Caused by: Unable to dial server fp-sbtk1a-20170919-017 (47.74.32.227:443): tlsdialer: DialWithDialer timed out
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/chained.(*proxy).dialInternal (dialer.go:190)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/chained.(*proxy).doDial (dialer.go:176)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/chained.(*proxy).Dial (dialer.go:131)
ERROR balancer: balancer.go:182   at github.com/getlantern/flashlight/balancer.(*Balancer).dialWithTimeout.func1 (balancer.go:212)
ERROR balancer: balancer.go:182   at runtime.goexit (asm_amd64.s:2086)
ERROR balancer: balancer.go:182 Caused by: tlsdialer: DialWithDialer timed out
```

**Comment by Mogegehshs** [comment]
同上，数分钟前蓝灯失效

**Comment by Chumomo** [comment]
+1

**Comment by baiking** [comment]
每到大会都这样，不是人家管不了🐽

**Comment by NogizakaZ** [comment]
+1

**Comment by wangxinshuo426** [comment]
我的也是！！！才刚刚续费两年别让我失望呀！！！

**Comment by fengzechen0615** [comment]
我的还能用，免费版

**Comment by Yyh3** [comment]
苹果电脑也是这个时间段用不了了，哭泣

**Comment by Kelvely** [comment]
+1

**Comment by avery-laird** [comment]
I'm having a similar issue, probably related:

```
 [op=fetch_config root_op=fetch_config]
Oct 05 14:17:05.760 - 3m47s DEBUG flashlight.config: fetcher.go:120 Config unchanged in cloud [config_changed=false op=fetch_config root_op=fetch_config]
Oct 05 14:17:05.760 - 3m47s DEBUG flashlight.config: config.go:218 Ignoring not modified response
Oct 05 14:17:08.295 - 3m50s DEBUG balancer: balancer.go:330 -------------------------- Dialer Stats ----------------------- [op=client_started root_op=client_started]
Oct 05 14:17:08.295 - 3m50s DEBUG balancer: balancer.go:335 fp-donyc3-20170909-006                 at     138.197.20.43:443 (t)  S: 5050 / 24192 (6)	F: 19142 / 24192 (0)	L:   354ms	BW: 2.76Mbps	DT:   354ms [op=client_started root_op=client_started]
Oct 05 14:17:08.296 - 3m50s DEBUG balancer: balancer.go:335 fp-doams3-20170910-012                 at    178.62.202.225:443 (t)  S: 4401 / 23328 (1)	F: 18927 / 23328 (0)	L:   225ms	BW: 0.52Mbps	DT:   225ms [op=client_started root_op=client_started]
Oct 05 14:17:08.296 - 3m50s DEBUG balancer: balancer.go:335 fp-doblr1-20170911-002                 at      139.59.73.53:443 (t)  S: 5116 / 24736 (8)	F: 19620 / 24736 (0)	L:   471ms	BW: 0.56Mbps	DT:   471ms [op=client_started root_op=client_started]
Oct 05 14:17:08.296 - 3m50s DEBUG balancer: balancer.go:335 fp-sbtk1a-20171005-122                 at    47.74.35.162:28036 (t)  S:  895 / 2997 (0)	F: 2102 / 2997 (5)	L:    86ms	BW: 3.21Mbps	DT:    86ms [op=client_started root_op=client_started]
Oct 05 14:17:08.296 - 3m50s DEBUG balancer: balancer.go:348 ------------------------ End Dialer Stats --------------------- [op=client_started root_op=client_started]
Oct 05 14:17:18.125 - 3m59s DEBUG chained: overhead.go:22 App Traffic: 0 B  Wire Traffic: 0 B  Overhead: NaN%
Oct 05 14:17:18.193 - 3m59s DEBUG chained: overhead.go:22 App Traffic: 0 B  Wire Traffic: 136 B  Overhead: +Inf%
Oct 05 14:17:18.295 - 4m0s DEBUG balancer: balancer.go:330 -------------------------- Dialer Stats ----------------------- [op=client_started root_op=client_started]
Oct 05 14:17:18.296 - 4m0s DEBUG balancer: balancer.go:335 fp-donyc3-20170909-006                 at     138.197.20.43:443 (t)  S: 5050 / 24192 (6)	F: 19142 / 24192 (0)	L:   354ms	BW: 2.76Mbps	DT:   354ms [op=client_started root_op=client_started]
Oct 05 14:17:18.296 - 4m0s DEBUG balancer: balancer.go:335 fp-doams3-20170910-012                 at    178.62.202.225:443 (t)  S: 4401 / 23328 (1)	F: 18927 / 23328 (0)	L:   225ms	BW: 0.52Mbps	DT:   225ms [op=client_started root_op=client_started]
Oct 05 14:17:18.296 - 4m0s Oct 05 14:17:18.296 - 4m0s DEBUG flashlight: main.go:139 i18n.UseOSLocale: "Not found any translations, locale not set"
DEBUG balancer: balancer.go:335 fp-doblr1-20170911-002                 at      139.59.73.53:443 (t)  S: 5116 / 24736 (8)	F: 19620 / 24736 (0)	L:   471ms	BW: 0.56Mbps	DT:   471ms [op=client_started root_op=client_started]
```

**Comment by yangzhiyao** [comment]
18+1不小, 之后不知道还能不能上…… :(

**Comment by nykeejune** [comment]
开会呢~不让用吧估计~~不仅蓝灯，其他的全挂了好像~

**Comment by Kiekerti** [comment]
天啊，200块对于学生来说不小的数目，前两天续费seed，seed就挂了，开通专业版蓝灯就挂了。希望运营商给点回复。

**Comment by avery-laird** [comment]
Everyone else with this problem also in China ATM? This could have something to do with the new restrictions. I know another friend's VPN stopped working, as well as ExpressVPN, all within a half hour of each other

**Comment by gmvp3** [comment]
都是郭德纲影响力太大

**Comment by yinhaofrancis** [comment]
据说今天第二弹

**Comment by wanciyang** [comment]
我的蓝灯也是刚才用不了了，不过xx-net挂的ipv6依然很坚挺，不知道还能撑多久！

**Comment by koala99** [comment]
闻鬼搞发布会，紧急屏蔽所有的vpn

**Comment by zhangyutong926** [comment]
Same problem here. Also, I'm a Lantern Pro user but it does not recognize it anymore.
[lantern.log](https://github.com/getlantern/lantern/files/1359717/lantern.log)
![image](https://user-images.githubusercontent.com/6694864/31233070-3efdf260-aa1e-11e7-8bdb-369140884bb8.png)

**Comment by yinhaofrancis** [comment]
看来这次的料比较大

**Comment by guoxiaoxu** [comment]
确实这次郭德纲的料给力，他们真害怕了

**Comment by linmiss** [comment]
mac也挂了。lantern server is boom boom boom. hope solve it!!!

**Comment by avery-laird** [comment]
Lantern just started working again for me. I'll see if it lasts

**Comment by nightheart310** [comment]
I just paid for a year today....

**Comment by huangwd15** [comment]
挂掉了

**Comment by baiking** [comment]
work again

**Comment by koala99** [comment]
发布会结束了。。。

**Comment by hardwigg** [comment]
What the hell is going on!

**Comment by zetaosun** [comment]
能用了，感谢郭德纲啊

**Comment by zetaosun** [comment]
能用了，感謝郭德綱啊

**Comment by fengzechen0615** [comment]
谁能告诉我，郭德纲什么梗

**Comment by hardwigg** [comment]
有些事不谈是个结，谈开是个疤

**Comment by yinhaofrancis** [comment]
+1

**Comment by Kiekerti** [comment]
第一次觉得活着真好，每天都是这样起起伏伏我怕心脏受不了

**Comment by zetaosun** [comment]
努力學習工作，移民才是正道

**Comment by yinhaofrancis** [comment]
哎！！！！！！！！！

**Comment by zaleGZL** [comment]
已经可以了

**Comment by Kelvely** [comment]
It's time to close this issue :D

**Comment by zchazc** [comment]
已经恢复了，如楼上所言，可以关掉了
