### ISSUE TITLE
Error resend buffer: i/o timeout

### ISSUE THREAD

**Issue by fffw** [getlantern/lantern#3866]
New in 2.1.1. Reported by more than one user.

It's a bit unusual as `Write` should seldomly time out. It also times out too soon (less than 1 sec). We set write deadline somewhere?

```
detour: detour.go:249 Error while resend buffer to <masked>:80: write tcp <masked>:49482-><masked>:443: i/o timeout
```

**Comment by fffw** [comment]
It fails immediately without any timeout. Confirmed that it also happen in binaries build with Go1.5.3.

**Comment by myleshorton** [comment]
Great catch @fffw. Should we release a 2.1.2?
